### PR TITLE
Numerical analysis

### PR DESCRIPTION
**Pull request by h-varma**
I have completed the given tasks for Numerical Analysis.  
Note that there could be a conflict when merging because I had to remove the transpose operation in the read_in_np function.

@omzoqasd and @jonasleitner: please take a look at the changes when you find the time.

### CODE REVIEW

**Comment by jonasleitner** [comment]
Most things look great :) (at least as far as I can tell :D)
I'm not 100% sure about the Autocorrelation function. But I don't know how to interpret the data, so.... 
And I didn't knew that numpy function before (I'm not 100% if it does the correct thing).

**Comment by h-varma** [comment]
Yeah, I wasn't entirely sure about it either. 
@omzoqasd can you maybe take a look at it and improve/fix the autocorrelation function, if necessary?

**Comment by jonasleitner** [comment]
I mean in theory you just would need to use sum_t [psi(0)*psi(t)]. I just don't know how to interpret the data. Whats the starting state and our time evolved state.

**Comment by h-varma** [comment]
Shouldn't the autocorrelation be maximum when we compare time 0 with itself? @jonasleitner I updated your code to reflect this.

Since I wasn't sure about what to expect with the data and the np.correlate(x, x, mode="full") function passed this sanity check, I hoped that it works. But clearly it was wrong. So yeah, you're right. It's better to compute the autocorrelation like this.

**Comment by jonasleitner** [comment]
the result looks way nicer and yes you are right about the Maximum at t=0.
With your changes you are basically copying the first column of the array (because the first row is 0 everywhere besides the first element). But I think it may be correct that way, since we may just have one occupied state that evolves in time

**Pull request merged**
